# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'düzenlemeye_devam.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1926, 1088)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 1921, 1081))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_ana = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget_ana.setObjectName("widget_ana")
        self.widget_2_ana = QtWidgets.QWidget(self.widget_ana)
        self.widget_2_ana.setGeometry(QtCore.QRect(0, 0, 1921, 1081))
        self.widget_2_ana.setStyleSheet("background-color: #2E2E2E;")
        self.widget_2_ana.setObjectName("widget_2_ana")
        self.groupBox_artunPanel = QtWidgets.QGroupBox(self.widget_2_ana)
        self.groupBox_artunPanel.setGeometry(QtCore.QRect(10, 10, 351, 71))
        self.groupBox_artunPanel.setStyleSheet("background-color: #1A1A1A; /* Siyah arka plan */\n"
"color: white;\n"
"font-size: 22pt;\n"
"font-weight: bold;\n"
"border: 1px solid white; /* Beyaz çerçeve */\n"
"border-radius: 10px; /* Yumuşak köşe */\n"
"padding: 5px;")
        self.groupBox_artunPanel.setObjectName("groupBox_artunPanel")
        self.label_logo = QtWidgets.QLabel(self.groupBox_artunPanel)
        self.label_logo.setGeometry(QtCore.QRect(20, -10, 201, 71))
        self.label_logo.setAcceptDrops(False)
        self.label_logo.setStyleSheet("border: none;\n"
"")
        self.label_logo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("../artun/Beyaz.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.comboBox_com = QtWidgets.QComboBox(self.groupBox_artunPanel)
        self.comboBox_com.setGeometry(QtCore.QRect(250, 0, 91, 31))
        self.comboBox_com.setStyleSheet("font: 6pt \"MS Shell Dlg 2\";")
        self.comboBox_com.setEditable(False)
        self.comboBox_com.setObjectName("comboBox_com")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_2_baud = QtWidgets.QComboBox(self.groupBox_artunPanel)
        self.comboBox_2_baud.setGeometry(QtCore.QRect(250, 40, 91, 31))
        self.comboBox_2_baud.setStyleSheet("font: 6pt \"MS Shell Dlg 2\";")
        self.comboBox_2_baud.setObjectName("comboBox_2_baud")
        self.comboBox_2_baud.addItem("")
        self.comboBox_2_baud.addItem("")
        self.comboBox_2_baud.addItem("")
        self.groupBox_2_dijital = QtWidgets.QGroupBox(self.widget_2_ana)
        self.groupBox_2_dijital.setGeometry(QtCore.QRect(10, 90, 621, 461))
        self.groupBox_2_dijital.setStyleSheet("background-color: #1A1A1A;\n"
"color: white;  /* Yazıları beyaz yaparak kontrast artırabilirsiniz */\n"
"border: 2px solid #ffffff;\n"
"font-size: 14pt;\n"
"font-weight: bold;\n"
"color: white;\n"
"border: none;")
        self.groupBox_2_dijital.setObjectName("groupBox_2_dijital")
        self.label_4_dijital = QtWidgets.QLabel(self.groupBox_2_dijital)
        self.label_4_dijital.setGeometry(QtCore.QRect(10, 30, 601, 421))
        self.label_4_dijital.setStyleSheet("QLabel {\n"
"    background-color: #333333;\n"
"    border: 2px solid #ffffff;\n"
"    border-radius: 10px;\n"
"    min-height: 100px;\n"
"    min-width: 200px;\n"
"    border: none;\n"
"}")
        self.label_4_dijital.setText("")
        self.label_4_dijital.setPixmap(QtGui.QPixmap("../../Pictures/Screenshots/Ekran görüntüsü 2025-04-28 201541.png"))
        self.label_4_dijital.setScaledContents(True)
        self.label_4_dijital.setObjectName("label_4_dijital")
        self.groupBox_3_analog = QtWidgets.QGroupBox(self.widget_2_ana)
        self.groupBox_3_analog.setGeometry(QtCore.QRect(10, 560, 621, 511))
        self.groupBox_3_analog.setStyleSheet("background-color: #1A1A1A;\n"
"color: white;  /* Yazıları beyaz yaparak kontrast artırabilirsiniz */\n"
"border: 2px solid #ffffff;\n"
"font-size: 14pt;\n"
"font-weight: bold;\n"
"color: white;\n"
"border: none;")
        self.groupBox_3_analog.setObjectName("groupBox_3_analog")
        self.label_5_analog = QtWidgets.QLabel(self.groupBox_3_analog)
        self.label_5_analog.setGeometry(QtCore.QRect(10, 30, 601, 471))
        self.label_5_analog.setStyleSheet("QLabel {\n"
"    background-color: #333333;\n"
"    border: 2px solid #ffffff;\n"
"    border-radius: 10px;\n"
"    min-height: 100px;\n"
"    min-width: 200px;\n"
"    border: none;\n"
"}")
        self.label_5_analog.setText("")
        self.label_5_analog.setPixmap(QtGui.QPixmap("../../Pictures/Screenshots/Ekran görüntüsü 2025-04-28 201547.png"))
        self.label_5_analog.setScaledContents(True)
        self.label_5_analog.setObjectName("label_5_analog")
        self.groupBox_4_harita = QtWidgets.QGroupBox(self.widget_2_ana)
        self.groupBox_4_harita.setGeometry(QtCore.QRect(840, 10, 561, 451))
        self.groupBox_4_harita.setStyleSheet("background-color: #1A1A1A;\n"
"color: white;  /* Yazıları beyaz yaparak kontrast artırabilirsiniz */\n"
"border: 2px solid #ffffff;\n"
"font-size: 14pt;\n"
"font-weight: bold;\n"
"color: white;\n"
"border: none;")
        self.groupBox_4_harita.setObjectName("groupBox_4_harita")
        self.label_6_harita = QtWidgets.QLabel(self.groupBox_4_harita)
        self.label_6_harita.setGeometry(QtCore.QRect(10, 30, 541, 411))
        self.label_6_harita.setStyleSheet(" background-color: #333333;\n"
" border: 2px solid #ffffff;\n"
" border-radius: 10px;\n"
" min-height: 100px;\n"
" min-width: 200px;\n"
"border: none;")
        self.label_6_harita.setText("")
        self.label_6_harita.setPixmap(QtGui.QPixmap("../../Pictures/Screenshots/Ekran görüntüsü 2025-04-28 202046.png"))
        self.label_6_harita.setObjectName("label_6_harita")
        self.groupBox_5_telemetre = QtWidgets.QGroupBox(self.widget_2_ana)
        self.groupBox_5_telemetre.setGeometry(QtCore.QRect(640, 0, 191, 551))
        self.groupBox_5_telemetre.setStyleSheet("background-color: #1A1A1A;\n"
"color: white;  /* Yazıları beyaz yaparak kontrast artırabilirsiniz */\n"
"border: 2px solid #ffffff;\n"
"font-size: 18pt;\n"
"font-weight: bold;\n"
"color: white;\n"
"border: none;")
        self.groupBox_5_telemetre.setObjectName("groupBox_5_telemetre")
        self.groupBox_7_yerdenHiz = QtWidgets.QGroupBox(self.groupBox_5_telemetre)
        self.groupBox_7_yerdenHiz.setGeometry(QtCore.QRect(80, 270, 91, 31))
        self.groupBox_7_yerdenHiz.setStyleSheet("font-size: 6pt;")
        self.groupBox_7_yerdenHiz.setObjectName("groupBox_7_yerdenHiz")
        self.label_8_yerdenHiz = QtWidgets.QLabel(self.groupBox_7_yerdenHiz)
        self.label_8_yerdenHiz.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.label_8_yerdenHiz.setMouseTracking(False)
        self.label_8_yerdenHiz.setTabletTracking(False)
        self.label_8_yerdenHiz.setAcceptDrops(False)
        self.label_8_yerdenHiz.setStyleSheet("QLabel {\n"
"    background-color: #2E2E2E;\n"
"    border: none;  /* Kenarlık yok */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;  /* Yazıları beyaz yapıyoruz */\n"
"}\n"
"")
        self.label_8_yerdenHiz.setText("")
        self.label_8_yerdenHiz.setScaledContents(False)
        self.label_8_yerdenHiz.setWordWrap(False)
        self.label_8_yerdenHiz.setOpenExternalLinks(False)
        self.label_8_yerdenHiz.setObjectName("label_8_yerdenHiz")
        self.groupBox_10_donusAcisi = QtWidgets.QGroupBox(self.groupBox_5_telemetre)
        self.groupBox_10_donusAcisi.setGeometry(QtCore.QRect(80, 350, 91, 31))
        self.groupBox_10_donusAcisi.setStyleSheet("font-size: 6pt;")
        self.groupBox_10_donusAcisi.setObjectName("groupBox_10_donusAcisi")
        self.label_11_donusAcisi = QtWidgets.QLabel(self.groupBox_10_donusAcisi)
        self.label_11_donusAcisi.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.label_11_donusAcisi.setStyleSheet("QLabel {\n"
"    background-color: #2E2E2E;\n"
"    border: none;  /* Kenarlık yok */\n"
"    border-radius: 10px;\n"
"    font-size: 12pt; "
"    min-width: 70px;"
"    min-height: 30px;"
"    padding: 10px;\n"
"    color: white;  /* Yazıları beyaz yapıyoruz */\n"
"}\n"
"\n"
"")
        self.label_11_donusAcisi.setText("")
        self.label_11_donusAcisi.setObjectName("label_11_donusAcisi")
        self.groupBox_11_dikeyHiz = QtWidgets.QGroupBox(self.groupBox_5_telemetre)
        self.groupBox_11_dikeyHiz.setGeometry(QtCore.QRect(80, 230, 91, 41))
        self.groupBox_11_dikeyHiz.setStyleSheet("font-size: 6pt;")
        self.groupBox_11_dikeyHiz.setObjectName("groupBox_11_dikeyHiz")
        self.label_12_dikeyHiz = QtWidgets.QLabel(self.groupBox_11_dikeyHiz)
        self.label_12_dikeyHiz.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.label_12_dikeyHiz.setStyleSheet("QLabel {\n"
"    background-color: #2E2E2E;\n"
"    border: none;  /* Kenarlık yok */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;  /* Yazıları beyaz yapıyoruz */\n"
"}\n"
"")
        self.label_12_dikeyHiz.setText("")
        self.label_12_dikeyHiz.setObjectName("label_12_dikeyHiz")
        self.groupBox_2_irtifa = QtWidgets.QGroupBox(self.groupBox_5_telemetre)
        self.groupBox_2_irtifa.setGeometry(QtCore.QRect(0, 270, 81, 41))
        self.groupBox_2_irtifa.setStyleSheet("font-size: 6pt;")
        self.groupBox_2_irtifa.setObjectName("groupBox_2_irtifa")
        self.label_2_irtifa = QtWidgets.QLabel(self.groupBox_2_irtifa)
        self.label_2_irtifa.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label_2_irtifa.setStyleSheet("""
    QLabel {
        background-color: #2E2E2E;
        border: none;
        border-radius: 10px;
        padding: 10px;
        color: white;
        font-size: 12pt;   /* eklendi */
        min-width: 70px;   /* eklendi */
        min-height: 30px;  /* eklendi */
    }
""")

        self.label_2_irtifa.setText("")
        self.label_2_irtifa.setObjectName("label_2_irtifa")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_5_telemetre)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 350, 81, 31))
        self.groupBox_5.setStyleSheet("font-size: 6pt;")
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label_5.setStyleSheet("QLabel {\n"
"    background-color: #2E2E2E;\n"
"    border: none;  /* Kenarlık yok */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;  /* Yazıları beyaz yapıyoruz */\n"
"}")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5_telemetre)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 390, 81, 31))
        self.groupBox_6.setStyleSheet("font-size: 6pt;")
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label_6.setStyleSheet("QLabel {\n"
"    background-color: #2E2E2E;\n"
"    border: none;  /* Kenarlık yok */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;  /* Yazıları beyaz yapıyoruz */\n"
"}")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_5_telemetre)
        self.groupBox_7.setGeometry(QtCore.QRect(80, 390, 91, 31))
        self.groupBox_7.setStyleSheet("font-size: 6pt;")
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.label_7.setStyleSheet("QLabel {\n"
"    background-color: #2E2E2E;\n"
"    border: none;  /* Kenarlık yok */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;  /* Yazıları beyaz yapıyoruz */\n"
"}")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.groupBox_3_batarya = QtWidgets.QGroupBox(self.groupBox_5_telemetre)
        self.groupBox_3_batarya.setGeometry(QtCore.QRect(0, 40, 171, 80))
        self.groupBox_3_batarya.setStyleSheet("font-size: 10pt;")
        self.groupBox_3_batarya.setObjectName("groupBox_3_batarya")
        self.label_3_batarya = QtWidgets.QLabel(self.groupBox_3_batarya)
        self.label_3_batarya.setGeometry(QtCore.QRect(10, 20, 151, 41))
        self.label_3_batarya.setStyleSheet("QLabel {\n"
"    background-color: #2E2E2E;\n"
"    border: none;  /* Kenarlık yok */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;  /* Yazıları beyaz yapıyoruz */\n"
"}")
        self.label_3_batarya.setText("")
        self.label_3_batarya.setObjectName("label_3_batarya")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_5_telemetre)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 100, 191, 71))
        self.groupBox_4.setStyleSheet("font-size: 10pt;")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 151, 41))
        self.label_4.setStyleSheet("QLabel {\n"
"    background-color: #2E2E2E;\n"
"    border: none;  /* Kenarlık yok */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;  /* Yazıları beyaz yapıyoruz */\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.groupBox_6_yukseklik = QtWidgets.QGroupBox(self.groupBox_5_telemetre)
        self.groupBox_6_yukseklik.setGeometry(QtCore.QRect(0, 160, 231, 71))
        self.groupBox_6_yukseklik.setStyleSheet("font-size: 10pt;")
        self.groupBox_6_yukseklik.setObjectName("groupBox_6_yukseklik")
        self.label_7_yukseklik = QtWidgets.QLabel(self.groupBox_6_yukseklik)
        self.label_7_yukseklik.setGeometry(QtCore.QRect(10, 20, 151, 41))
        self.label_7_yukseklik.setStyleSheet("QLabel {\n"
"    background-color: #2E2E2E;\n"
"    border: none;  /* Kenarlık yok */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;  /* Yazıları beyaz yapıyoruz */\n"
"}\n"
"")
        self.label_7_yukseklik.setText("")
        self.label_7_yukseklik.setScaledContents(False)
        self.label_7_yukseklik.setObjectName("label_7_yukseklik")
        self.groupBox_8_MavaMesafe = QtWidgets.QGroupBox(self.groupBox_5_telemetre)
        self.groupBox_8_MavaMesafe.setGeometry(QtCore.QRect(0, 230, 91, 41))
        self.groupBox_8_MavaMesafe.setStyleSheet("font-size: 6pt;")
        self.groupBox_8_MavaMesafe.setObjectName("groupBox_8_MavaMesafe")
        self.label_9_mavaMesafe = QtWidgets.QLabel(self.groupBox_8_MavaMesafe)
        self.label_9_mavaMesafe.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label_9_mavaMesafe.setStyleSheet("QLabel {\n"
"    background-color: #2E2E2E;\n"
"    border: none;  /* Kenarlık yok */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;  /* Yazıları beyaz yapıyoruz */\n"
"}\n"
"")
        self.label_9_mavaMesafe.setText("")
        self.label_9_mavaMesafe.setObjectName("label_9_mavaMesafe")
        self.groupBox_9_wpyeMesafe = QtWidgets.QGroupBox(self.groupBox_5_telemetre)
        self.groupBox_9_wpyeMesafe.setGeometry(QtCore.QRect(0, 310, 81, 31))
        self.groupBox_9_wpyeMesafe.setStyleSheet("font-size: 6pt;")
        self.groupBox_9_wpyeMesafe.setObjectName("groupBox_9_wpyeMesafe")
        self.label_10_wpyeMesafe = QtWidgets.QLabel(self.groupBox_9_wpyeMesafe)
        self.label_10_wpyeMesafe.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label_10_wpyeMesafe.setStyleSheet("QLabel {\n"
"    background-color: #2E2E2E;\n"
"    border: none;  /* Kenarlık yok */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;  /* Yazıları beyaz yapıyoruz */\n"
"}\n"
"\n"
"")
        self.label_10_wpyeMesafe.setText("")
        self.label_10_wpyeMesafe.setObjectName("label_10_wpyeMesafe")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_5_telemetre)
        self.groupBox.setGeometry(QtCore.QRect(80, 310, 91, 31))
        self.groupBox.setStyleSheet("font-size: 6pt;")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.label.setStyleSheet("QLabel {\n"
"    background-color: #2E2E2E;\n"
"    border: none;  /* Kenarlık yok */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;  /* Yazıları beyaz yapıyoruz */\n"
"}\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_5_telemetre)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 430, 81, 31))
        self.groupBox_8.setStyleSheet("font-size: 6pt;")
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox_8)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label_8.setStyleSheet("QLabel {\n"
"    background-color: #2E2E2E;\n"
"    border: none;  /* Kenarlık yok */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;  /* Yazıları beyaz yapıyoruz */\n"
"}")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_5_telemetre)
        self.groupBox_10.setGeometry(QtCore.QRect(80, 430, 91, 31))
        self.groupBox_10.setStyleSheet("font-size: 6pt;")
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_9 = QtWidgets.QLabel(self.groupBox_10)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.label_9.setStyleSheet("QLabel {\n"
"    background-color: #2E2E2E;\n"
"    border: none;  /* Kenarlık yok */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;  /* Yazıları beyaz yapıyoruz */\n"
"}")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_5_telemetre)
        self.groupBox_11.setGeometry(QtCore.QRect(0, 470, 81, 31))
        self.groupBox_11.setStyleSheet("font-size: 6pt;")
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_10 = QtWidgets.QLabel(self.groupBox_11)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label_10.setStyleSheet("QLabel {\n"
"    background-color: #2E2E2E;\n"
"    border: none;  /* Kenarlık yok */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;  /* Yazıları beyaz yapıyoruz */\n"
"}")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_5_telemetre)
        self.groupBox_12.setGeometry(QtCore.QRect(80, 470, 101, 31))
        self.groupBox_12.setStyleSheet("font-size: 6pt;")
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_11 = QtWidgets.QLabel(self.groupBox_12)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.label_11.setStyleSheet("QLabel {\n"
"    background-color: #2E2E2E;\n"
"    border: none;  /* Kenarlık yok */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;  /* Yazıları beyaz yapıyoruz */\n"
"}")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_5_telemetre)
        self.groupBox_13.setGeometry(QtCore.QRect(0, 510, 91, 31))
        self.groupBox_13.setStyleSheet("font-size: 6pt;")
        self.groupBox_13.setObjectName("groupBox_13")
        self.label_12 = QtWidgets.QLabel(self.groupBox_13)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label_12.setStyleSheet("QLabel {\n"
"    background-color: #2E2E2E;\n"
"    border: none;  /* Kenarlık yok */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;  /* Yazıları beyaz yapıyoruz */\n"
"}")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_5_telemetre)
        self.groupBox_14.setGeometry(QtCore.QRect(80, 510, 91, 31))
        self.groupBox_14.setStyleSheet("font-size: 6pt;")
        self.groupBox_14.setObjectName("groupBox_14")
        self.label_13 = QtWidgets.QLabel(self.groupBox_14)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.label_13.setStyleSheet("QLabel {\n"
"    background-color: #2E2E2E;\n"
"    border: none;  /* Kenarlık yok */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;  /* Yazıları beyaz yapıyoruz */\n"
"}")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.tabWidget_butonlar = QtWidgets.QTabWidget(self.widget_2_ana)
        self.tabWidget_butonlar.setGeometry(QtCore.QRect(1410, 10, 501, 291))
        self.tabWidget_butonlar.setStyleSheet("")
        self.tabWidget_butonlar.setObjectName("tabWidget_butonlar")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget_3_actions = QtWidgets.QWidget(self.tab)
        self.widget_3_actions.setGeometry(QtCore.QRect(0, 0, 491, 261))
        self.widget_3_actions.setStyleSheet("")
        self.widget_3_actions.setObjectName("widget_3_actions")
        self.comboBox_3_Loiter_Unlim = QtWidgets.QComboBox(self.widget_3_actions)
        self.comboBox_3_Loiter_Unlim.setGeometry(QtCore.QRect(10, 30, 121, 41))
        self.comboBox_3_Loiter_Unlim.setStyleSheet("font-size: 10pt;\n"
"color: white;")
        self.comboBox_3_Loiter_Unlim.setObjectName("comboBox_3_Loiter_Unlim")
        self.comboBox_3_Loiter_Unlim.addItem("")
        self.comboBox_3_Loiter_Unlim.addItem("")
        self.comboBox_3_Loiter_Unlim.addItem("")
        self.comboBox_3_Loiter_Unlim.addItem("")
        self.comboBox_3_Loiter_Unlim.addItem("")
        self.comboBox_3_Loiter_Unlim.addItem("")
        self.comboBox_3_Loiter_Unlim.addItem("")
        self.comboBox_3_Loiter_Unlim.addItem("")
        self.comboBox_3_Loiter_Unlim.addItem("")
        self.comboBox_3_Loiter_Unlim.addItem("")
        self.comboBox_3_Loiter_Unlim.addItem("")
        self.comboBox_3_Loiter_Unlim.addItem("")
        self.comboBox_3_Loiter_Unlim.addItem("")
        self.comboBox_3_Loiter_Unlim.addItem("")
        self.comboBox_3_Loiter_Unlim.addItem("")
        self.comboBox_4_home = QtWidgets.QComboBox(self.widget_3_actions)
        self.comboBox_4_home.setGeometry(QtCore.QRect(10, 80, 121, 41))
        self.comboBox_4_home.setStyleSheet("font-size: 10pt;\n"
"color: white;")
        self.comboBox_4_home.setObjectName("comboBox_4_home")
        self.comboBox_4_home.addItem("")
        self.comboBox_5_loiter = QtWidgets.QComboBox(self.widget_3_actions)
        self.comboBox_5_loiter.setGeometry(QtCore.QRect(10, 130, 121, 41))
        self.comboBox_5_loiter.setStyleSheet("font-size: 10pt;\n"
"color: white;")
        self.comboBox_5_loiter.setObjectName("comboBox_5_loiter")
        self.comboBox_5_loiter.addItem("")
        self.comboBox_5_loiter.addItem("")
        self.comboBox_5_loiter.addItem("")
        self.comboBox_5_loiter.addItem("")
        self.comboBox_5_loiter.addItem("")
        self.comboBox_5_loiter.addItem("")
        self.comboBox_5_loiter.addItem("")
        self.comboBox_5_loiter.addItem("")
        self.comboBox_5_loiter.addItem("")
        self.comboBox_5_loiter.addItem("")
        self.comboBox_5_loiter.addItem("")
        self.comboBox_5_loiter.addItem("")
        self.comboBox_5_loiter.addItem("")
        self.comboBox_5_loiter.addItem("")
        self.comboBox_5_loiter.addItem("")
        self.comboBox_6_mavlink = QtWidgets.QComboBox(self.widget_3_actions)
        self.comboBox_6_mavlink.setGeometry(QtCore.QRect(10, 180, 121, 41))
        self.comboBox_6_mavlink.setStyleSheet("font-size: 10pt;\n"
"color: white;")
        self.comboBox_6_mavlink.setObjectName("comboBox_6_mavlink")
        self.comboBox_6_mavlink.addItem("")
        self.comboBox_6_mavlink.addItem("")
        self.comboBox_6_mavlink.addItem("")
        self.comboBox_6_mavlink.addItem("")
        self.comboBox_6_mavlink.addItem("")
        self.pushButton_doAction = QtWidgets.QPushButton(self.widget_3_actions)
        self.pushButton_doAction.setGeometry(QtCore.QRect(140, 30, 101, 41))
        self.pushButton_doAction.setStyleSheet("font-size: 10pt;\n"
"color: white;")
        self.pushButton_doAction.setObjectName("pushButton_doAction")
        self.pushButton_2_setWp = QtWidgets.QPushButton(self.widget_3_actions)
        self.pushButton_2_setWp.setGeometry(QtCore.QRect(140, 80, 101, 41))
        self.pushButton_2_setWp.setStyleSheet("font-size: 10pt;\n"
"color: white;")
        self.pushButton_2_setWp.setObjectName("pushButton_2_setWp")
        self.pushButton_3_setMode = QtWidgets.QPushButton(self.widget_3_actions)
        self.pushButton_3_setMode.setGeometry(QtCore.QRect(140, 130, 101, 41))
        self.pushButton_3_setMode.setStyleSheet("font-size: 10pt;\n"
"color: white;")
        self.pushButton_3_setMode.setObjectName("pushButton_3_setMode")
        self.pushButton_4_setMount = QtWidgets.QPushButton(self.widget_3_actions)
        self.pushButton_4_setMount.setGeometry(QtCore.QRect(140, 180, 101, 41))
        self.pushButton_4_setMount.setStyleSheet("font-size: 10pt;\n"
"color: white;")
        self.pushButton_4_setMount.setObjectName("pushButton_4_setMount")
        self.pushButton_5_auto = QtWidgets.QPushButton(self.widget_3_actions)
        self.pushButton_5_auto.setGeometry(QtCore.QRect(250, 30, 111, 41))
        self.pushButton_5_auto.setStyleSheet("font-size: 10pt;\n"
"color: white;")
        self.pushButton_5_auto.setObjectName("pushButton_5_auto")
        self.pushButton_6_loiter = QtWidgets.QPushButton(self.widget_3_actions)
        self.pushButton_6_loiter.setGeometry(QtCore.QRect(250, 80, 111, 41))
        self.pushButton_6_loiter.setStyleSheet("font-size: 10pt;\n"
"color: white;")
        self.pushButton_6_loiter.setObjectName("pushButton_6_loiter")
        self.pushButton_7_rtl = QtWidgets.QPushButton(self.widget_3_actions)
        self.pushButton_7_rtl.setGeometry(QtCore.QRect(250, 130, 111, 41))
        self.pushButton_7_rtl.setStyleSheet("font-size: 10pt;\n"
"color: white;")
        self.pushButton_7_rtl.setObjectName("pushButton_7_rtl")
        self.pushButton_8_joystick = QtWidgets.QPushButton(self.widget_3_actions)
        self.pushButton_8_joystick.setGeometry(QtCore.QRect(250, 180, 111, 41))
        self.pushButton_8_joystick.setStyleSheet("font-size: 10pt;\n"
"color: white;")
        self.pushButton_8_joystick.setObjectName("pushButton_8_joystick")
        self.pushButton_9_setHome = QtWidgets.QPushButton(self.widget_3_actions)
        self.pushButton_9_setHome.setGeometry(QtCore.QRect(370, 30, 111, 41))
        self.pushButton_9_setHome.setStyleSheet("font-size: 10pt;\n"
"color: white;")
        self.pushButton_9_setHome.setObjectName("pushButton_9_setHome")
        self.pushButton_10_restart = QtWidgets.QPushButton(self.widget_3_actions)
        self.pushButton_10_restart.setGeometry(QtCore.QRect(370, 80, 111, 41))
        self.pushButton_10_restart.setStyleSheet("font-size: 10pt;\n"
"color: white;")
        self.pushButton_10_restart.setObjectName("pushButton_10_restart")
        self.pushButton_11_rawSensor = QtWidgets.QPushButton(self.widget_3_actions)
        self.pushButton_11_rawSensor.setGeometry(QtCore.QRect(370, 130, 111, 41))
        self.pushButton_11_rawSensor.setMouseTracking(False)
        self.pushButton_11_rawSensor.setTabletTracking(False)
        self.pushButton_11_rawSensor.setAutoFillBackground(False)
        self.pushButton_11_rawSensor.setStyleSheet("font-size: 10pt;\n"
"color: white;")
        self.pushButton_11_rawSensor.setObjectName("pushButton_11_rawSensor")
        self.pushButton_12_armDisarm = QtWidgets.QPushButton(self.widget_3_actions)
        self.pushButton_12_armDisarm.setGeometry(QtCore.QRect(370, 180, 111, 41))
        self.pushButton_12_armDisarm.setStyleSheet("font-size: 10pt;\n"
"color: white;")
        self.pushButton_12_armDisarm.setObjectName("pushButton_12_armDisarm")
        self.tabWidget_butonlar.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 801, 291))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 799, 289))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.widget_4_preFlight = QtWidgets.QWidget(self.scrollAreaWidgetContents_4)
        self.widget_4_preFlight.setGeometry(QtCore.QRect(0, 0, 491, 261))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4_preFlight.sizePolicy().hasHeightForWidth())
        self.widget_4_preFlight.setSizePolicy(sizePolicy)
        self.widget_4_preFlight.setObjectName("widget_4_preFlight")
        self.label_13_camera = QtWidgets.QLabel(self.widget_4_preFlight)
        self.label_13_camera.setGeometry(QtCore.QRect(10, 230, 421, 21))
        self.label_13_camera.setStyleSheet("border: 1px solid black; /* Beyaz çerçeve */\n"
"color: white;")
        self.label_13_camera.setObjectName("label_13_camera")
        self.label_14_verify = QtWidgets.QLabel(self.widget_4_preFlight)
        self.label_14_verify.setGeometry(QtCore.QRect(10, 10, 421, 21))
        self.label_14_verify.setStyleSheet("border: 1px solid black; /* Beyaz çerçeve */\n"
"color: white;")
        self.label_14_verify.setObjectName("label_14_verify")
        self.label_15_telemetry = QtWidgets.QLabel(self.widget_4_preFlight)
        self.label_15_telemetry.setGeometry(QtCore.QRect(10, 50, 421, 21))
        self.label_15_telemetry.setStyleSheet("border: 1px solid black; /* Beyaz çerçeve */\n"
"color: white;")
        self.label_15_telemetry.setObjectName("label_15_telemetry")
        self.label_16_gpsSat = QtWidgets.QLabel(self.widget_4_preFlight)
        self.label_16_gpsSat.setGeometry(QtCore.QRect(10, 30, 421, 21))
        self.label_16_gpsSat.setStyleSheet("border: 1px solid black; /* Beyaz çerçeve */\n"
"color: white;")
        self.label_16_gpsSat.setObjectName("label_16_gpsSat")
        self.label_17_mode = QtWidgets.QLabel(self.widget_4_preFlight)
        self.label_17_mode.setGeometry(QtCore.QRect(10, 90, 421, 21))
        self.label_17_mode.setStyleSheet("border: 1px solid black; /* Beyaz çerçeve */\n"
"color: white;")
        self.label_17_mode.setObjectName("label_17_mode")
        self.label_18_tail = QtWidgets.QLabel(self.widget_4_preFlight)
        self.label_18_tail.setGeometry(QtCore.QRect(10, 130, 421, 21))
        self.label_18_tail.setStyleSheet("border: 1px solid black; /* Beyaz çerçeve */\n"
"color: white;")
        self.label_18_tail.setObjectName("label_18_tail")
        self.label_19_battery = QtWidgets.QLabel(self.widget_4_preFlight)
        self.label_19_battery.setGeometry(QtCore.QRect(10, 70, 421, 21))
        self.label_19_battery.setStyleSheet("border: 1px solid black; /* Beyaz çerçeve */\n"
"color: white;")
        self.label_19_battery.setObjectName("label_19_battery")
        self.label_20_check = QtWidgets.QLabel(self.widget_4_preFlight)
        self.label_20_check.setGeometry(QtCore.QRect(10, 110, 421, 21))
        self.label_20_check.setStyleSheet("border: 1px solid black; /* Beyaz çerçeve */\n"
"color: white;")
        self.label_20_check.setObjectName("label_20_check")
        self.label_21_allinput = QtWidgets.QLabel(self.widget_4_preFlight)
        self.label_21_allinput.setGeometry(QtCore.QRect(10, 150, 421, 21))
        self.label_21_allinput.setStyleSheet("border: 1px solid black; /* Beyaz çerçeve */\n"
"color: white;")
        self.label_21_allinput.setObjectName("label_21_allinput")
        self.label_22_allRoll = QtWidgets.QLabel(self.widget_4_preFlight)
        self.label_22_allRoll.setGeometry(QtCore.QRect(10, 170, 421, 21))
        self.label_22_allRoll.setStyleSheet("border: 1px solid black; /* Beyaz çerçeve */\n"
"color: white;")
        self.label_22_allRoll.setObjectName("label_22_allRoll")
        self.label_23_centerOf = QtWidgets.QLabel(self.widget_4_preFlight)
        self.label_23_centerOf.setGeometry(QtCore.QRect(10, 190, 421, 21))
        self.label_23_centerOf.setStyleSheet("border: 1px solid black; /* Beyaz çerçeve */\n"
"color: white;")
        self.label_23_centerOf.setObjectName("label_23_centerOf")
        self.label_24_servo = QtWidgets.QLabel(self.widget_4_preFlight)
        self.label_24_servo.setGeometry(QtCore.QRect(10, 210, 421, 21))
        self.label_24_servo.setStyleSheet("border: 1px solid black; /* Beyaz çerçeve */\n"
"color: white;")
        self.label_24_servo.setObjectName("label_24_servo")
        self.checkBox_verify = QtWidgets.QCheckBox(self.widget_4_preFlight)
        self.checkBox_verify.setGeometry(QtCore.QRect(420, 10, 81, 20))
        self.checkBox_verify.setText("")
        self.checkBox_verify.setObjectName("checkBox_verify")
        self.checkBox_2_gpsSat = QtWidgets.QCheckBox(self.widget_4_preFlight)
        self.checkBox_2_gpsSat.setGeometry(QtCore.QRect(420, 30, 81, 20))
        self.checkBox_2_gpsSat.setText("")
        self.checkBox_2_gpsSat.setObjectName("checkBox_2_gpsSat")
        self.checkBox_3_telemetry = QtWidgets.QCheckBox(self.widget_4_preFlight)
        self.checkBox_3_telemetry.setGeometry(QtCore.QRect(420, 50, 81, 20))
        self.checkBox_3_telemetry.setText("")
        self.checkBox_3_telemetry.setObjectName("checkBox_3_telemetry")
        self.checkBox_4_battery = QtWidgets.QCheckBox(self.widget_4_preFlight)
        self.checkBox_4_battery.setGeometry(QtCore.QRect(420, 70, 81, 20))
        self.checkBox_4_battery.setText("")
        self.checkBox_4_battery.setObjectName("checkBox_4_battery")
        self.checkBox_5_mode = QtWidgets.QCheckBox(self.widget_4_preFlight)
        self.checkBox_5_mode.setGeometry(QtCore.QRect(420, 90, 81, 20))
        self.checkBox_5_mode.setText("")
        self.checkBox_5_mode.setObjectName("checkBox_5_mode")
        self.checkBox_6_check = QtWidgets.QCheckBox(self.widget_4_preFlight)
        self.checkBox_6_check.setGeometry(QtCore.QRect(420, 110, 81, 20))
        self.checkBox_6_check.setText("")
        self.checkBox_6_check.setObjectName("checkBox_6_check")
        self.checkBox_7_tail = QtWidgets.QCheckBox(self.widget_4_preFlight)
        self.checkBox_7_tail.setGeometry(QtCore.QRect(420, 130, 81, 20))
        self.checkBox_7_tail.setText("")
        self.checkBox_7_tail.setObjectName("checkBox_7_tail")
        self.checkBox_8_allinput = QtWidgets.QCheckBox(self.widget_4_preFlight)
        self.checkBox_8_allinput.setGeometry(QtCore.QRect(420, 150, 81, 20))
        self.checkBox_8_allinput.setText("")
        self.checkBox_8_allinput.setObjectName("checkBox_8_allinput")
        self.checkBox_9_allRoll = QtWidgets.QCheckBox(self.widget_4_preFlight)
        self.checkBox_9_allRoll.setGeometry(QtCore.QRect(420, 170, 81, 20))
        self.checkBox_9_allRoll.setText("")
        self.checkBox_9_allRoll.setObjectName("checkBox_9_allRoll")
        self.checkBox_10_centerOf = QtWidgets.QCheckBox(self.widget_4_preFlight)
        self.checkBox_10_centerOf.setGeometry(QtCore.QRect(420, 190, 81, 20))
        self.checkBox_10_centerOf.setText("")
        self.checkBox_10_centerOf.setObjectName("checkBox_10_centerOf")
        self.checkBox_11_servo = QtWidgets.QCheckBox(self.widget_4_preFlight)
        self.checkBox_11_servo.setGeometry(QtCore.QRect(420, 210, 81, 20))
        self.checkBox_11_servo.setText("")
        self.checkBox_11_servo.setObjectName("checkBox_11_servo")
        self.checkBox_12_camera = QtWidgets.QCheckBox(self.widget_4_preFlight)
        self.checkBox_12_camera.setGeometry(QtCore.QRect(420, 230, 81, 20))
        self.checkBox_12_camera.setText("")
        self.checkBox_12_camera.setObjectName("checkBox_12_camera")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.tabWidget_butonlar.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.widget_ana)

        self.retranslateUi(Form)
        self.tabWidget_butonlar.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox_com.setItemText(0, _translate("Form", "COM1"))
        self.comboBox_com.setItemText(1, _translate("Form", "COM2"))
        self.comboBox_com.setItemText(2, _translate("Form", "COM3"))
        self.comboBox_2_baud.setItemText(0, _translate("Form", "9600"))
        self.comboBox_2_baud.setItemText(1, _translate("Form", "57600"))
        self.comboBox_2_baud.setItemText(2, _translate("Form", "115200"))
        self.groupBox_2_dijital.setTitle(_translate("Form", "Dijital"))
        self.groupBox_3_analog.setTitle(_translate("Form", "Analog"))
        self.groupBox_4_harita.setTitle(_translate("Form", "Harita"))
        self.groupBox_5_telemetre.setTitle(_translate("Form", "Telemetre"))
        self.groupBox_7_yerdenHiz.setTitle(_translate("Form", "Yerden Hız"))
        self.groupBox_10_donusAcisi.setTitle(_translate("Form", "Dönüş Açısı"))
        self.groupBox_11_dikeyHiz.setTitle(_translate("Form", "Dikey Hız"))
        self.groupBox_2_irtifa.setTitle(_translate("Form", "irtifa"))
        self.groupBox_5.setTitle(_translate("Form", "uydu sayısı"))
        self.groupBox_6.setTitle(_translate("Form", "yer hızı "))
        self.groupBox_7.setTitle(_translate("Form", "eğim"))
        self.groupBox_3_batarya.setTitle(_translate("Form", "batarya voltajı"))
        self.groupBox_4.setTitle(_translate("Form", "akım"))
        self.groupBox_6_yukseklik.setTitle(_translate("Form", "Yükseklik"))
        self.groupBox_8_MavaMesafe.setTitle(_translate("Form", "MAV\'a Mesafe"))
        self.groupBox_9_wpyeMesafe.setTitle(_translate("Form", "WP\'ye Mesafe"))
        self.groupBox.setTitle(_translate("Form", "hava hızı"))
        self.groupBox_8.setTitle(_translate("Form", "roll    "))
        self.groupBox_10.setTitle(_translate("Form", "rssi"))
        self.groupBox_11.setTitle(_translate("Form", "sinyal gücü"))
        self.groupBox_12.setTitle(_translate("Form", "aktifleşme süresi"))
        self.groupBox_13.setTitle(_translate("Form", "EKF durumu"))
        self.groupBox_14.setTitle(_translate("Form", "yaw"))
        self.comboBox_3_Loiter_Unlim.setItemText(0, _translate("Form", "Loiter_Unlim"))
        self.comboBox_3_Loiter_Unlim.setItemText(1, _translate("Form", "Return_To_Launch"))
        self.comboBox_3_Loiter_Unlim.setItemText(2, _translate("Form", "Preflight_Calibration"))
        self.comboBox_3_Loiter_Unlim.setItemText(3, _translate("Form", "Preflight_Calibration"))
        self.comboBox_3_Loiter_Unlim.setItemText(4, _translate("Form", "Mission_Start"))
        self.comboBox_3_Loiter_Unlim.setItemText(5, _translate("Form", "Preflight_Reboot_Shutdown"))
        self.comboBox_3_Loiter_Unlim.setItemText(6, _translate("Form", "Trigger_Camera"))
        self.comboBox_3_Loiter_Unlim.setItemText(7, _translate("Form", "System_Time"))
        self.comboBox_3_Loiter_Unlim.setItemText(8, _translate("Form", "Battery_Reset"))
        self.comboBox_3_Loiter_Unlim.setItemText(9, _translate("Form", "ADSB_Out_Ident"))
        self.comboBox_3_Loiter_Unlim.setItemText(10, _translate("Form", "Scripting_cmd_stop_and_restart"))
        self.comboBox_3_Loiter_Unlim.setItemText(11, _translate("Form", "HighLatency_Enable"))
        self.comboBox_3_Loiter_Unlim.setItemText(12, _translate("Form", "HighLatency_Disable"))
        self.comboBox_3_Loiter_Unlim.setItemText(13, _translate("Form", "Toggle_Safety_Switch"))
        self.comboBox_3_Loiter_Unlim.setItemText(14, _translate("Form", "Do_Parachute"))
        self.comboBox_4_home.setItemText(0, _translate("Form", "0(Home)"))
        self.comboBox_5_loiter.setItemText(0, _translate("Form", "Loiter"))
        self.comboBox_5_loiter.setItemText(1, _translate("Form", "Auto"))
        self.comboBox_5_loiter.setItemText(2, _translate("Form", "Manual"))
        self.comboBox_5_loiter.setItemText(3, _translate("Form", "CIRCLE"))
        self.comboBox_5_loiter.setItemText(4, _translate("Form", "STABILIZE"))
        self.comboBox_5_loiter.setItemText(5, _translate("Form", "TRAINING"))
        self.comboBox_5_loiter.setItemText(6, _translate("Form", "ACRO"))
        self.comboBox_5_loiter.setItemText(7, _translate("Form", "FBWA"))
        self.comboBox_5_loiter.setItemText(8, _translate("Form", "FBWB"))
        self.comboBox_5_loiter.setItemText(9, _translate("Form", "CRUISE"))
        self.comboBox_5_loiter.setItemText(10, _translate("Form", "AUTOTUNE"))
        self.comboBox_5_loiter.setItemText(11, _translate("Form", "RTL"))
        self.comboBox_5_loiter.setItemText(12, _translate("Form", "TAKEOFF"))
        self.comboBox_5_loiter.setItemText(13, _translate("Form", "Guided"))
        self.comboBox_5_loiter.setItemText(14, _translate("Form", "QSTABILIZE"))
        self.comboBox_6_mavlink.setItemText(0, _translate("Form", "MavLink Targeting"))
        self.comboBox_6_mavlink.setItemText(1, _translate("Form", "Retracted"))
        self.comboBox_6_mavlink.setItemText(2, _translate("Form", "Neutral"))
        self.comboBox_6_mavlink.setItemText(3, _translate("Form", "RC Targeting"))
        self.comboBox_6_mavlink.setItemText(4, _translate("Form", "GPS Point"))
        self.pushButton_doAction.setText(_translate("Form", "Do Action"))
        self.pushButton_2_setWp.setText(_translate("Form", "Set WP"))
        self.pushButton_3_setMode.setText(_translate("Form", "Set Mode"))
        self.pushButton_4_setMount.setText(_translate("Form", "Set Mount"))
        self.pushButton_5_auto.setText(_translate("Form", "Auto"))
        self.pushButton_6_loiter.setText(_translate("Form", "Loiter"))
        self.pushButton_7_rtl.setText(_translate("Form", "RTL"))
        self.pushButton_8_joystick.setText(_translate("Form", "Joystick"))
        self.pushButton_9_setHome.setText(_translate("Form", "Set Home Alt"))
        self.pushButton_10_restart.setText(_translate("Form", "Restart Mission"))
        self.pushButton_11_rawSensor.setText(_translate("Form", "Raw Sensor View"))
        self.pushButton_12_armDisarm.setText(_translate("Form", "Arm/Disarm"))
        self.tabWidget_butonlar.setTabText(self.tabWidget_butonlar.indexOf(self.tab), _translate("Form", "Actions"))
        self.label_13_camera.setText(_translate("Form", "Camera is on and ready to fly?"))
        self.label_14_verify.setText(_translate("Form", "Verify GPS"))
        self.label_15_telemetry.setText(_translate("Form", "Telemetry Signal"))
        self.label_16_gpsSat.setText(_translate("Form", "Gps Sat Count"))
        self.label_17_mode.setText(_translate("Form", "Mode"))
        self.label_18_tail.setText(_translate("Form", "Tail and wings secured?"))
        self.label_19_battery.setText(_translate("Form", "Battery Level"))
        self.label_20_check.setText(_translate("Form", "Check Altitude"))
        self.label_21_allinput.setText(_translate("Form", "All servos respond to input?"))
        self.label_22_allRoll.setText(_translate("Form", "All servos respond to pitch and roll?"))
        self.label_23_centerOf.setText(_translate("Form", "Center of gravity at indicated point?"))
        self.label_24_servo.setText(_translate("Form", "Servo linkages are secure?"))
        self.tabWidget_butonlar.setTabText(self.tabWidget_butonlar.indexOf(self.tab_2), _translate("Form", "PreFlight"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
